GET http://localhost:8080/insuranceproducts/getAll

###

GET http://localhost:8080/insuranceproducts/getById?id=6

###

GET http://localhost:8080/insuranceproducts/getById/4

###

POST http://localhost:8080/insuranceproducts/save
Content-Type: application/json

{
  "id": 0,
  "insuranceCompanyName": "Insurance company №8",
  "basicTariff": 4150,
  "image":"{{mediaName}}"

}


###

POST http://localhost:8080/insuranceproducts/removeById?id=1

###

POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="media.png"
Content-Type: image/png

###

GET http://localhost:8080/calculate?idRegion=10&idAgeAndExperience=2&idEnginePower=4&idLimitStatus=1&idSeasonalityStatus=8&idInsuranceCompany=2&insuranceTerm=1

###

POST http://localhost:8080/sales/register
Content-Type: application/json

{
  "insuranceCompanyName": "Insurance Company №3",
  "userName": "Jonn",
  "userSurname": "Smitt",
  "vinNumberCar": "ZC45545NT4544",
  "phoneNumber": "9503432343",
  "email": "smitt@mail.ru",
  "region":  "Казань",
  "bankCardNumber": "2344 3456 6789 3456",
  "insurancePremiumPrice": 5340
}